name: Atualizar Precos Diariamente

on:
  schedule:
    # Roda todos os dias às 09:00 UTC (06:00 no horário de Brasília)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permite que você clique no botão "Run workflow" para testar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      with:
        persist-credentials: true # Mantém as credenciais para o Push

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install requests urllib3

    - name: Executar script de atualizacao
      run: python Atualizar_precos.py

    - name: Salvar alteracoes no JSON
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configura a identidade do robô que fará o commit
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Adiciona o arquivo modificado
        git add produtos.json
        
        # Tenta fazer o commit, mas não trava se não houver mudanças
        git commit -m "Auto: Atualizacao de precos (com centavos)" || echo "Sem alteracoes para salvar"
        
        # Usa o Token de segurança para autorizar o envio (Push) de volta ao repositório
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push
