name: Atualizar Precos Diariamente

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install requests urllib3

    - name: Executar script de atualizacao
      run: python Atualizar_precos.py

    - name: Salvar alteracoes no JSON
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add produtos.json
        
        # Verifica se houve mudança real. Se não houve, ele apenas avisa e não dá erro.
        if git diff --staged --quiet; then
          echo "Nenhuma alteração de preço encontrada hoje."
        else
          git commit -m "Auto: Atualizacao de precos"
          # Usa o token para garantir permissão de escrita no push
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        fi
