name: Atualizar Precos Diariamente

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write # Garante explicitamente permissão de escrita

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Pega o histórico completo para evitar erros de push

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install requests urllib3

    - name: Executar script de atualizacao
      run: python Atualizar_precos.py

    - name: Salvar alteracoes no JSON
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add produtos.json
        # Só faz o commit se houver mudanças reais
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Atualizacao de precos" && git push origin main)
